services:
  worldcup:
    build: .
    ports:
      - "80:3000"
    environment:
      - PORT=3000
      - JWT_SECRET="dc82ff369e0ecfd73283747a579c116d29721ce361ba2ebbd14303912f519f30"
      - DATABASE_URL=file:/data/prod.db
    volumes:
      - ./data:/data
    restart: unless-stopped